#
filebeat.prospectors:
- 
  paths:
    - /opt/logs/pj-api/*.log
    #- E:\logs\pj_business\*.log
  document_type: log_yooeee_test
  input_type: log 
  multiline.pattern: '^\[ELK=]'
  multiline.negate: true
  multiline.match: after
  ignore_older: 24h
  fields:
    service: product_pj_front_api

name: 192.168.0.43

#----------------------------- Logstash output --------------------------------
output.logstash:
  # The Logstash hosts
  #hosts: ["localhost:5044"]
  hosts: ["192.168.0.52:5044"]